// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!pOVQPOOQnQPOOOOQO'#Cr'#CrOVQPO,58}OVQPO,59POVQPO,59SOVQPO,59UOVQPO,59XO!PQPO1G.iOOQO1G.k1G.kO!eQPO1G.nO!yQPO1G.pO#_QPO1G.s",
  stateData: "#|~OPOS~ORQOSQOTQOUQOZQO`QOcQO~OWROYSO]TO_UObVO~OYSOWVi]Vi_VibVidVi~OWROYSO][i_[ib[id[i~OWROYSO]TO_^ib^id^i~OWROYSO]TO_UObaidai~OcZU]_bS]~",
  goto: "!SgPPPPPPPhPhPPhPhPPhPPPPp]QORSTUVQPOQWRQXSQYTQZUR[V",
  nodeNames: "⚠ Space Program Number Property Member Boolean AdditiveExpression AdditiveOperator MultiplicativeExpression MultiplicativeOperator Not ComparisonExpression ComparisonOperator EqualityExpression EqualityOperator String LogicalExpression LogicalOperator Until",
  maxTerm: 22,
  skippedNodes: [0,1],
  repeatNodeCount: 0,
  tokenData: "9f~RlXY!yYZ!y]^!ypq!yuv#[z{#[{|#a}!O#a!O!P#f!P!Q#[!Q![$Q!]!^$e!c!}%c#T#U%t#U#Y%c#Y#Z(h#Z#[*x#[#]%c#]#^.s#^#`%c#`#a2k#a#b%c#b#c4S#c#d5j#d#h%c#h#i6R#i#j7R#j#o%c~#OSP~XY!yYZ!y]^!ypq!y~#aOY~~#fOW~~#iQ!c!}#o#T#o#o~#tST~!Q![#o!c!}#o#R#S#o#T#o#o~$VQR~!O!P$]!Q![$Q~$bPR~!Q![$]~$hTO!]$e!]!^$w!^;'S$e;'S;=`%]<%lO$e~$|T`~O!]$e!]!^$w!^;'S$e;'S;=`%]<%lO$e~%`P;=`<%l$e~%hSS~!Q![%c!c!}%c#R#S%c#T#o%c~%yWS~!Q![%c!c!}%c#R#S%c#T#b%c#b#c&c#c#h%c#h#i'_#i#o%c~&hUS~!Q![%c!c!}%c#R#S%c#T#W%c#W#X&z#X#o%c~'RSb~S~!Q![%c!c!}%c#R#S%c#T#o%c~'dTS~pq's!Q![%c!c!}%c#R#S%c#T#o%c~'vP#`#a'y~'|P#X#Y(P~(SP#T#U(V~(YP#g#h(]~(`P#h#i(c~(hO]~~(mTS~!Q![%c!c!}%c#R#S%c#T#U(|#U#o%c~)RUS~!Q![%c!c!}%c#R#S%c#T#`%c#`#a)e#a#o%c~)jUS~!Q![%c!c!}%c#R#S%c#T#g%c#g#h)|#h#o%c~*RUS~!Q![%c!c!}%c#R#S%c#T#X%c#X#Y*e#Y#o%c~*lSU~S~!Q![%c!c!}%c#R#S%c#T#o%c~*}US~!Q![%c!c!}%c#R#S%c#T#f%c#f#g+a#g#o%c~+fUS~!Q![%c!c!}%c#R#S%c#T#X%c#X#Y+x#Y#o%c~+}TS~!Q![%c!c!}%c#R#S%c#T#U,^#U#o%c~,cUS~!Q![%c!c!}%c#R#S%c#T#h%c#h#i,u#i#o%c~,zUS~!Q![%c!c!}%c#R#S%c#T#X%c#X#Y-^#Y#o%c~-cUS~!Q![%c!c!}%c#R#S%c#T#f%c#f#g-u#g#o%c~-zTS~pq.Z!Q![%c!c!}%c#R#S%c#T#o%c~.^P#h#i.a~.dP#[#].g~.jP#T#U.m~.pP#b#c(c~.xUS~!Q![%c!c!}%c#R#S%c#T#g%c#g#h/[#h#o%c~/cT_~S~pq/r!Q![%c!c!}%c#R#S%c#T#o%c~/uS#T#U0R#Z#[0_#`#a1Z#b#c1m~0UP#h#i0X~0[Ppq's~0bP#f#g0e~0hP#X#Y0k~0nP#T#U0q~0tP#h#i0w~0zP#X#Y0}~1QP#f#g1T~1WPpq.Z~1^P#X#Y1a~1dP#g#h1g~1jP#g#h1T~1pP#c#d1s~1vQpq1|#h#i2f~2PP#a#b2S~2VP#c#d2Y~2]P#f#g2`~2cP#X#Y1T~2kO_~~2pUS~!Q![%c!c!}%c#R#S%c#T#X%c#X#Y3S#Y#o%c~3XUS~!Q![%c!c!}%c#R#S%c#T#g%c#g#h3k#h#o%c~3pUS~!Q![%c!c!}%c#R#S%c#T#g%c#g#h-u#h#o%c~4XUS~!Q![%c!c!}%c#R#S%c#T#c%c#c#d4k#d#o%c~4pVS~pq1|!Q![%c!c!}%c#R#S%c#T#h%c#h#i5V#i#o%c~5^SZ~S~!Q![%c!c!}%c#R#S%c#T#o%c~5oUS~!Q![%c!c!}%c#R#S%c#T#f%c#f#g&z#g#o%c~6WUS~!Q![%c!c!}%c#R#S%c#T#f%c#f#g6j#g#o%c~6oUS~!Q![%c!c!}%c#R#S%c#T#i%c#i#j)|#j#o%c~7WUS~!Q![%c!c!}%c#R#S%c#T#b%c#b#c7j#c#o%c~7oUS~!Q![%c!c!}%c#R#S%c#T#h%c#h#i8R#i#o%c~8WUS~!Q![%c!c!}%c#R#S%c#T#]%c#]#^8j#^#o%c~8oUS~!Q![%c!c!}%c#R#S%c#T#`%c#`#a9R#a#o%c~9YSc~S~!Q![%c!c!}%c#R#S%c#T#o%c",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  tokenPrec: 127
})
